### ISSUE TITLE
Prebuilt `lib-font.browser.js` bundle throws `Unexpected token 'export'` error

### ISSUE THREAD

**Issue by nuthinking** [Pomax/lib-font#131]
When loaded or embedded as a simple script (not `module`) it throws: `lib-font.browser.js:1 Uncaught SyntaxError: Unexpected token 'export' (at lib-font.browser.js:1:81241)`

**Comment by Pomax** [comment]
The README.md explicitly calls this out: https://github.com/Pomax/lib-font#tddr

**Comment by nuthinking** [comment]
Ops, I thought that because it was a bundle it didn't need to be a module. Sorry about that!

**Comment by nuthinking** [comment]
@Pomax if I add the type attribute as `module` I then get: `Failed to resolve module specifier 'zlib'`

**Comment by Pomax** [comment]
Heh, also called out in the README.md but probably not as obvious: https://github.com/Pomax/lib-font#why-dont-woffwoff2 since browsers (frustratingly) don't come with a convenient `Compression` object even though they fully support deflate/inflate, zip/unzip, and brotli/unbrotli because of server compression.
