### ISSUE TITLE
Font.js improvement/expansion priorities

### ISSUE THREAD

**Issue by RoelN** [Pomax/lib-font#77]
As discussed, a small list of issues of what tools like Wakamai Fondue would need from Font.js to become _superpowered!_

I've noted them in order of priority as I see this, keeping an eye on universal benefit. Suggested formats are just suggestions, always up for something better!

- [ ] Get characters per GSUB feature:
  - [x]  if there is a "fi" and a "fl" ligature, return `["fi", "fl"]`.
  - [x] Singe substitutions (e.g. `[["a", "a.alt"], ["b", "b.alt"]]`). Similar for alternate substutions?
  - [ ] Lookups with lookahead/input/backtrack. Not sure how to best return this. Maybe keep it low level? `{ ahead: ["a", "b"], input: ["q"], back: ["z"] }`
- [ ] Get characters per GPOS feature:
  - [ ] ???
- [x] Get features for the default langsys ([issue](https://github.com/Pomax/Font.js/issues/72))
- [x] Get name when feature references `UINameID` ([issue](https://github.com/Pomax/Font.js/issues/73))
- [x] COLR/CPAL minor issues
  - [x] [here](https://github.com/Pomax/Font.js/issues/75) and
  - [x] [here](https://github.com/Pomax/Font.js/issues/76)

**Comment by Pomax** [comment]
I recall we also discussed the following tasks:

- making the code run in both node and the browser via tactical shims/dynamic imports
- adding testing (mocha)
- offering a full (with gzip+brotli) and lean (without) fontjs
- npm publishing of font.js
- adding rollup, using a target that will work for older Node versions (i.e. v10 through v13)

**Comment by Pomax** [comment]
I've also push a minor update on the master branch that shims the `fetch` call so that it works in both Node and the browser, with the relevant code over in https://github.com/Pomax/Font.js/blob/master/Font.js#L7-L34, primarily so I could run some tests using Node.js rather than the browser.

I've also updated all instances of `window` to use [globalThis]()https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis instead, and added a `document` check to the stylesheet building function, because we don't need a stylesheet if there is no `document`.

**Comment by Pomax** [comment]
Example of testing in Node with those shims in place:
```
import { Font } from "../../Font.js";

const myFont = new Font(`Bungee`);

// When the font's up and loaded in, let's do some testing!
function doSomeFontThings(evt) {
    const font = evt.detail.font;

    const CPAL = font.opentype.tables.CPAL;
    console.log(CPAL.colorRecords);
}

myFont.onerror = evt => console.error(evt);
myFont.onload = evt => doSomeFontThings(evt);
myFont.src = `./protected/bungee/BungeeColor.ttf`;
```

**Comment by Pomax** [comment]
turns out the `LookupTable` class doesn't actually implement sensible subtable parsing right now, so in order to address GSUB issues I've filed https://github.com/Pomax/Font.js/issues/88, for actually implementing the correct GSUB subtable code.

(and the GPOS after that)

**Comment by Pomax** [comment]
@RoelN there's a few checkboxes left open. GSUB is mostly implemented (well... the data modelling side at least =), but I haven't done anything explicitly for GPOS yet (so none of its formats have code yet). I'm also not quite sure about the lookups with lookahead/input/backtrack, technically the tables are there so that might be enough, and then projects that rely on fontjs for the datamodel have to add their own code for the lookahead/backtracking?

**Comment by Pomax** [comment]
@RoelN I've updated the first comment to split GPOS from GSUB, is there's actually anything that is "needed" from GPOS?

**Comment by RoelN** [comment]
I suppose GPOS is more functional, e.g. it makes specific character combinations look as intended. This as opposed to GSUB which can introduce completely different designs.

That said, for a tool like Font.js and Wakamai Fondue, it would be ideal to just report on GPOS and let the user decide if this data is valuable to them. I literally got zero requests for this in Wakamai Fondue, as it doesn't report on GPOS at all currently, so I imagine this would be low priority.

**Comment by RoelN** [comment]
Since many of these issues have either been addressed, or have their separate issues (e.g. GPOS re-added to https://github.com/Pomax/lib-font/issues/45), I'm closing this issue!
